config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :messages
  resources :replies
  resources :posts
  resources :organizations
  resources :users
  resources :sessions
  resources :matches
  resources :administrators
  resources :password_resets, only: [:new, :create, :edit, :update]


  root "welcome#index"
  get "/home", to: "welcome#index"
  get "/match", to: "posts#match"
  get "/users/:id/:section", to: "users#show", constraints: { section: /(home|match|activity|match|organizations)/ }
  get "posts/:query/search", to: "posts#index", as: "post_search"
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get 'password_resets/new'
  get 'password_resets/edit'

  post "/posts/new", to: "posts#create"
  post "/sessions/new", to: "sessions#create"
  post "/matches/:id", to: "messages#create"
  post "/posts/:id", to: "replies#create"
  post "/organizations/:id", to: "organizations#create"
  post "/matches/:id/accept", to: "matches#accept", as: "accept_match"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :reset_token
    has_many :organizations
    has_many :posts
    has_many :messages
    has_secure_password
    paginates_per 10

    validates :first_name, presence: true 
    validates :last_name, presence: true
    validate :email_or_oauth_present?
    validates :password, length: { minimum: 6 }, allow_nil: true, unless: proc { |x| x.password.blank? }


    def email_or_oauth_present?
        if !self[:email] && !self[:oauth_id]
          errors.add(:email, "No email/oauth present")
        end
        if self[:email] && !self[:oauth_id]
          if self[:email].blank?
            errors.add(:email, "can't be blank")
          elsif !self[:email].match?(/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i)
            errors.add(:email, "invalid format")
          end
        end
    end

    def full_name
        "#{self[:first_name]} #{self[:last_name]}"
    end

    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
      SecureRandom.urlsafe_base64
    end

    def create_reset_digest
      self.reset_token = User.new_token
      update_attribute(:reset_digest,  User.digest(reset_token))
      update_attribute(:reset_sent_at, Time.zone.now)
    end
    def send_password_reset_email
      UserMailer.password_reset(self).deliver_now
    end

    searchkick

    def search_data
        {
            full_name: full_name,
            email: email
        }
    end 

    User.reindex
  
    private
  
      # Converts email to all lower-case.
      def downcase_email
        self.email = email.downcase
      end
  
      # Creates and assigns the activation token and digest.
      def create_activation_digest
        self.activation_token  = User.new_token
        self.activation_digest = User.digest(activation_token)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in!, only: [:show, :index]
    skip_before_action :verify_authenticity_token, only: [:create]

    def index
        search = params[:search].present? ? params[:search] : nil
        @users = if search
            User.search(search)
        else
            User.all
        end
        @users = User.where(id: @users.pluck(:id)).order("LOWER(last_name)").page(params[:page])
    end

    def show
        @user = User.find(params[:id])
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            flash[:notice] = "Your account was created!"
            redirect_to @user
        else
            flash[:alert] = @user.errors.full_messages.join(", ")
            render 'new'
        end
    end
    
    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :admin)
    end 

end

app/helpers/users_helper.rb
module UsersHelper
    def get_picture(user, classes, size)
        if user.picture
            url = user.picture
        else
            url = "https://secure.gravatar.com/avatar/#{Digest::MD5::hexdigest(user.email.downcase)}?d=identicon"
        end
        image_tag(url, alt: user.full_name, class: classes, width: size)
    end
end

app/views/users/_activity.html.erb
<div class="card">
    <h5 class="card-header"><%= fa_icon "comments", text: "Your Activity" %></h5>
    <div class="card-body">
        <% posts = Post.all.where(user_id: current_user.id) %>
        <% if posts.size > 0 %>
            <% posts.each do | post | %>
                <h5 class="card-title">
                    <%= post.title %>
                </h5>
                <p>
                    <%= link_to(post) do %>
                        <span class="text-blue"><%= fa_icon "info-circle", text: "Show" %></span>
                    <% end %>
                    <%= link_to(edit_post_path(post)) do %>
                        <span class="text-blue"><%= fa_icon "pencil", text: "Edit" %></span>
                    <% end %>
                    <%= link_to(post, method: :delete, data: {confirm: "Are you sure that you want to delete this?"}) do %>
                        <span class="text-blue"><%= fa_icon "bomb", text: "Delete" %></span>
                    <% end %>
                </p>
            <% end %>
        <% else %>
            <h5>You haven't created any posts yet!</h5>
        <% end %>
        <%= link_to("/posts/new", class: "ml-2 d-inline") do %>
            <span class="text-blue"><%= fa_icon "plus", text: "Create a Post" %></span>
        <% end %>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'mb-1 form-control' %>

    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'mb-1 form-control' %>

    <%= form.label :email %>
    <%= form.email_field :email, class: 'mb-1 form-control' %>

    <%= form.label :password %>
    <%= form.password_field :password, class: 'mb-1 form-control' %>

    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'mb-1 form-control' %>
    <br>
    <%= form.submit "Sign Up", class: 'btn btn-primary' %>
<% end %>

app/views/users/_home.html.erb
<div class="container">
    <div class="card-body">
        <div class="row ml-1 mr-1">
            <div class="col-9">
                <h5><%= @user.full_name %></h5>
                <p><%= @user.email %></p>
                <% if @user.id == current_user.id %>
                    <%= button_to "Request Help", new_post_path, :method => "get", class: "btn btn-primary" %>
                    <%= button_to "Offer Help", new_post_path, :method => "get", class: "btn btn-primary mt-2" %>
                    <%= button_to "Register an Organization", new_organization_path, :method => "get", class: "btn btn-primary mt-2" %>
                <% else %>
                    <%= render '/layouts/match_form', match: Match.new, user1_id: current_user.id, user2_id: @user.id, post_id: -1 %>
                <% end %> 
            </div>
            <div class="col-3 text-center">
                <div>
                    <%= get_picture(@user, "", 80) %>
                </div>
                <% if @user.id == current_user.id %>
                    <div class="mt-3">
                        <%= link_to("https://en.gravatar.com", class: "ml-2 d-inline a text-reset") do %>
                            <span class="text-blue"><%= fa_icon "file-photo-o", text: "Edit Avatar" %></span>
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/_match.html.erb
<% def populate_list(confirmed, sent_requests, received_requests, match) %>
    <% if confirmed == true %>
        <% sent_requests << match %>
    <% else %>
        <% received_requests << match %>
    <% end %>
<% end %>

<% def populate_section(match) %>
    <h5 class="card-title">
        <% if match.user1_id == current_user.id %>
            <%= User.find(match.user2_id).first_name %> 
        <% else %>
            <%= User.find(match.user1_id).first_name %>
        <% end %>
    </h5>
    <p>
        <% Post.all.where(id: match.post_id).each do |post| %>
            <%= post.title %>
        <% end %>
    </p>
<% end %>

<div class="card">
    <h5 class="card-header"><%= fa_icon "handshake-o", text: "Your Matches" %></h5>
    <div class="card-body">
        <% confirmed_matches = [] %>
        <% received_requests = [] %>
        <% sent_requests = [] %>
        <% matches = Match.all.where(user1_id: current_user.id).or(Match.all.where(user2_id: current_user.id)) %>
        <% if matches.size > 0 %>
            <% matches.each do | match | %>
                <% if match.confirmed? %>
                    <% confirmed_matches << match %>
                <% else %>
                    <% if current_user.id == match.user1_id %>
                        <% populate_list(match.user1_confirmed, sent_requests, received_requests, match) %>
                    <% else %>
                        <% populate_list(match.user2_confirmed, sent_requests, received_requests, match) %>
                    <% end %>
                <% end %>
                </p>
            <% end %>
            <% if confirmed_matches.size > 0 %>
                <h4>Confirmed Matches</h4>
                <% confirmed_matches.each do |match| %>
                    <% populate_section(match) %>
                    <%= link_to(match) do %>
                        <span class="text-blue"><%= fa_icon "info-circle", text: "Show" %></span>
                    <% end %>
                <% end %>
                <br><br>
            <% end %>
            <% if sent_requests.size > 0 %>
                <h4>Sent Requests</h4>
                <% sent_requests.each do |match| %>
                    <% populate_section(match) %>
                    <% if match.user1_id == current_user.id %>
                        <%= link_to(user_path(User.find(match.user2_id))) do %>
                            <span class="text-blue"><%= fa_icon "info-circle", text: "Show" %></span>
                        <% end %>
                    <% else %>
                        <%= link_to(user_path(User.find(match.user1_id))) do %>
                            <span class="text-blue"><%= fa_icon "info-circle", text: "Show" %></span>
                        <% end %>
                    <% end %>
                <% end %>
                <br><br>
            <% end %>
            <% if received_requests.size > 0 %>
                <h4>Received Requests</h4>
                <% received_requests.each do |match| %>
                    <% populate_section(match) %>
                    <%= link_to(accept_match_path(match), method: :post) do %>
                        <span class="text-blue"><%= fa_icon "heart", text: "Accept" %></span>
                    <% end %>
                    <%= link_to(match, method: :delete, data: {confirm: "Are you sure that you want to delete this?"}) do %>
                        <span class="text-blue"><%= fa_icon "times", text: "Deny" %></span>
                    <% end %>
                <% end %>
                <br><br>
            <% end %>
        <% else %>
            <h5>You haven't created any matches yet!</h5>
        <% end %>
        <%= link_to("/matches", class: "ml-2 d-inline") do %>
            <span class="text-blue"><%= fa_icon "search", text: "Search for Matches" %></span>
        <% end %>
    </div>
</div>

app/views/users/_message.html.erb
<div class="card">
    <h5 class="card-header"><%= fa_icon "envelope", text: "Your Messages" %></h5>
    <div class="card-body">
        <% matches = Match.all.where(user1_id: current_user.id).or(Match.all.where(user2_id: current_user.id))%>
        <% if matches.size > 0 %>
            <% matches.each do | match | %>
                <% if match.confirmed? %>
                    <h5 class="card-title">
                        <% if match.user1_id == current_user.id %>
                            <%= User.find(match.user2_id).first_name %> 
                        <% else %>
                            <%= User.find(match.user1_id).first_name %>
                        <% end %>
                    </h5>
                    <p>
                        <%= link_to(match) do %>
                            <span class="text-blue"><%= fa_icon "info-circle", text: "Show" %></span>
                        <% end %>
                    </p>
                <% end %>
            <% end %>
        <% else %>
            <h5>You can't message anyone, because you don't have any matches yet!</h5>
        <% end %>
        <%= link_to("/matches", class: "ml-2 d-inline") do %>
            <span class="text-blue"><%= fa_icon "search", text: "Search for Matches" %></span>
        <% end %>
    </div>
</div>

app/views/users/_organizations.html.erb
<div class="card">
    <h5 class="card-header"><%= fa_icon "users", text: "Your Organizations" %></h5>
    <div class="card-body">
        <% admin_organizations = Administrator.all.where(user_id: current_user.id) %>
        <% if admin_organizations.size > 0 %>
            <% admin_organizations.each do |admin_organization| %>
                <% organization = Organization.find(admin_organization.organization_id) %>
                <h5 class="card-title"><%= organization.name %></h5>
                <p>
                    <%= link_to(organization) do %>
                        <span class="text-blue"><%= fa_icon "info-circle", text: "Show" %></span>
                    <% end %>
                </p>
            <% end %>
        <% else %>
            <h5>You haven't created any organizations yet!</h5>
        <% end %>
        <%= link_to("/organizations/new", class: "ml-2 d-inline") do %>
            <span class="text-blue"><%= fa_icon "plus", text: "Create an Organization" %></span>
        <% end %>
    </div>
</div>

app/views/users/_sidemenu.html.erb
    <ul>
      </li>
            <%= link_to(user_path(current_user.id, section: "home"), class: "nav-link text-reset") do %>
                <%= fa_icon "id-card", text: "Home" %>
            <% end %>
        </li>
        <li>
            <%= link_to(user_path(current_user.id, section: "message"), class: "nav-link text-reset") do %>
                <%= fa_icon "envelope", text: "Messages" %>
            <% end %>
        </li>
        <li>
            <%= link_to(user_path(current_user.id, section: "activity"), class: "nav-link text-reset") do %>
                <%= fa_icon "comments", text: "Activity" %>
            <% end %>
        </li>
        <li>
            <%= link_to(user_path(current_user.id, section: "match"), class: "nav-link text-reset") do %>
                <%= fa_icon "handshake-o", text: "Matches" %>
            <% end %>
        </li>
        <li>
            <%= link_to(user_path(current_user.id, section: "organizations"), class: "nav-link text-reset") do %>
                <%= fa_icon "users", text: "Organizations" %>
            <% end %>
        </li>
    </ul>

app/views/users/index.html.erb
<div class="container">
    <div class ="d-flex justify-content-between flex-wrap">
        <div class="w-30 ml-3">
            <%= image_tag("users.svg", size: "200x200")%>
        </div>
        <div class="mr-auto p-5">
            <h1 class="d-inline w-50 heading">Users</h1>
            <p>Find users by name or email</p>
        </div>
    </div>
</div>
<hr>
<div class="row">
    <div class="col ms-12">
    <%= form_with(model: @user, url: users_path, method: :get, :class => "form-inline justify-content-center") do |form| %>
        <%= search_field_tag :search, params[:search], placeholder: "Keyword Search", class: "form-control" %>
    <%= form.submit "Search", class: "btn btn-primary ml-2" %>
    <% end %>
    </div>
</div>
<br>

<div class="row">
<table class="table">
    <thead>
        <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td>
            <%= user.full_name %>
            </td>
            <td><%= user.email %></td>
            <td>
                <%= link_to(user) do %>
                    <span class="text-blue"><%= fa_icon "info-circle", text: "Show" %></span>
                <% end %>
            </td>
        </tr>
        <% end %>
        </tbody>
    </table>
    <%= paginate @users %>
</div>

app/views/users/matches.html.erb
<% user_matches = Match.where(user1_id: current_user.id).or(Match.where(user2_id: current_user.id)) %>

<% user_matches.each |match| do %>
    <% if match.user1_id == current_user.id %>
        <%= match.user2_id.first_name %> 
    <% else %>
        <%= match.user1_id.first_name %>
    <% end %>
    <%= match.post_id.content %>
<% end %>

app/views/users/new.html.erb
<div class="container">
    <div class ="d-flex justify-content-between flex-wrap">
        <div class="w-30 ml-3">
            <%= image_tag("welcome.svg", size: "220x200")%>
        </div>
        <div class="w-50 heading mr-auto ml-5 pt-5">
            <h1 class="d-inline">Sign up below</h1>
        </div>
    </div>
</div>
<%= render 'form', user: User.new %>
<p>Already have an account? Sign in <span class="text-blue"><%= link_to "here!", "/sessions/new" %></span></p>

app/views/users/show.html.erb
<div class="container">
    <div class ="d-flex justify-content-between flex-wrap">
        <div class="w-30 ml-3">
            <%= image_tag("profile.svg", size: "200x200")%>
        </div>
        <div class="w-50 heading mr-auto p-5">
            <h1 class="d-inline">Profile</h1>
        </div>
    </div>
</div>
<hr>
<div class="row">
  <% if @user.id == current_user.id %>
    <div class="col-sm-2 justify-content-start">
      <%= render partial: "sidemenu" %>
    </div>
  <% end %>
  <div class="col-sm-10 justify-content-center">
    <% valid_partials = ["home", "match", "activity", "message", "organizations"] %>
    <% if params[:section] == nil || !valid_partials.include?(params[:section]) %>
      <%= render partial: "home"%>
    <% else %>
      <%= render partial: params[:section] %>
    <% end %>
  </div>
</div>