config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :messages
  resources :replies
  resources :posts
  resources :organizations
  resources :users
  resources :sessions
  resources :matches
  resources :administrators
  resources :password_resets, only: [:new, :create, :edit, :update]


  root "welcome#index"
  get "/home", to: "welcome#index"
  get "/match", to: "posts#match"
  get "/users/:id/:section", to: "users#show", constraints: { section: /(home|match|activity|match|organizations)/ }
  get "posts/:query/search", to: "posts#index", as: "post_search"
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get 'password_resets/new'
  get 'password_resets/edit'

  post "/posts/new", to: "posts#create"
  post "/sessions/new", to: "sessions#create"
  post "/matches/:id", to: "messages#create"
  post "/posts/:id", to: "replies#create"
  post "/organizations/:id", to: "organizations#create"
  post "/matches/:id/accept", to: "matches#accept", as: "accept_match"
end

app/views/layouts/_alert.html.erb
<div class="position-absolute toasts mt-5 p-4">
    <div class="notifs" data-controller="notify" data-user="<%= current_user ? current_user.id : -1 %>">
    </div>
</div>

<% if notice %>
    <div class="alert alert-primary mb-4" role="alert" id="notice">
        <strong><%= fa_icon "exclamation-circle", text: "Info: " %></strong><%= notice %>
    </div>
<% elsif alert %> 
    <div class="alert alert-warning mb-4" role="alert" id="alert">
        <strong><%= fa_icon "exclamation-triangle", text: "Warning! " %></strong><%= alert %>
    </div>
<% else %> 
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer pt-3">
    <div class="container">
        <p class="text-right text-muted">With <%= fa_icon "heart" %> by Sana team</p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
  <%= link_to(root_url, class: "navbar-brand") do %>
    <%= fa_icon "heartbeat", text: "Sana" %>
  <% end %>
  <button class="navbar-toggler navbar-brand" type="button" data-toggle="collapse" data-target="#navbar-sana" aria-controls="navbar-sana" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbar-sana">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to(posts_path, class: "nav-link navbar-brand") do %>
          Forum
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(matches_path, class: "nav-link navbar-brand") do %>
          Match
        <% end %>
      </li>
      <li class="nav-item">
      <%= link_to(users_path, class: "nav-link navbar-brand") do %>
        Users
      <% end %>
    </li>
    </ul>
    <ul class="navbar-nav">
      <% if logged_in? %>
        <% if current_user.admin %>
          <li class="nav-item ">
            <%= link_to(rails_admin_path, class: "nav-link navbar-brand") do %>
              Admin
            <% end %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle navbar-brand" href="#" id="navbar-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.first_name %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">
            <%= link_to(user_path(current_user), class: "dropdown-item") do %>
              Profile
            <% end %>
            <%= link_to(session_path(session), class: "dropdown-item", method: :delete) do %>
              Log Out
            <% end %>
          </div>
        </li>
      <% else %> 
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle navbar-brand" href="#" id="navbar-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Guest
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">
            <%= link_to(new_session_path, class: "dropdown-item") do %>
             Log In
            <% end %>    
            <%= link_to(new_user_path, class: "dropdown-item") do %>
              Sign Up
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_match_form.html.erb
<%= form_with model: match do |form| %>
    <% if Post.where(id: post_id).count == 1 %> 
        <%= form.hidden_field :post_id, :value => post_id %>
    <% end %>
    <%= form.hidden_field :user1_id, :value => user1_id %>
    <%= form.hidden_field :user2_id, :value => user2_id %>
    <%= form.hidden_field :user1_confirmed, :value => true %>
    <%= form.submit "Request Match", class: 'btn btn-primary mb-2' %>
<% end %>

app/views/layouts/_minitexts.html.erb
<% models.each do |model| %>
  <div class="row">
      <div role="alert" aria-live="assertive" aria-atomic="true" class="toast <%= model.user_id == current_user.id ? "mr-auto" : "ml-auto" %> mb-4" data-autohide="false">
          <div class="toast-header">
            <% user = User.find(model.user_id) %>
            <%= get_picture(user, "rounded mr-2", 20) %>
            <strong class="mr-auto"><%= user.full_name %></strong>
            <small><%= to_datetime_string(model.created_at) %></small>
          </div>
          <div class="toast-body">
            <p><%= model.content %></p>
            <% if owns_model?(model) %>
              <div><%= render "/layouts/operations", edit_route: "", destroy_route: model %></div>
            <% end %>
          </div>
        </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to("#", class: "navbar-brand") do %>
    <%= fa_icon "users", text: "Sana" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-sana" aria-controls="navbar-sana" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbar-sana">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to(posts_path, class: "nav-link") do %>
          <%= fa_icon "comments", text: "Forum" %> 
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(match_path, class: "nav-link") do %>
          <%= fa_icon "handshake-o", text: "Match" %>
        <% end %>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to(session_path(session), class: "nav-link", method: :delete) do %>
            <%= fa_icon "user-times", text: "Log out" %>
          <% end %>
        </li>
      <% else %> 
        <li class="nav-item">
          <%= link_to(new_session_path, class: "nav-link") do %>
            <%= fa_icon "user", text: "Log in" %>
          <% end %>    
        </li>
        <li class="nav-item">
          <%= link_to(new_user_path, class: "nav-link") do %>
            <%= fa_icon "user-plus", text: "Sign up" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  
</nav>

app/views/layouts/_operations.html.erb
<% unless edit_route.blank? %>
    <%= link_to(edit_route) do %>
        <span class="text-blue"><%= fa_icon "pencil", text: "Edit" %></span>
    <% end %>
<% end %>

<% unless destroy_route.blank? %>
    <%= link_to(destroy_route, method: :delete, data: {confirm: "Are you sure that you want to delete this?"}) do %>
        <span class="text-blue"><%= fa_icon "bomb", text: "Delete" %></span>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sana</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <script src="https://hammerjs.github.io/dist/hammer.min.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100&display=swap" rel="stylesheet">
</head>

  <body>
      <%= render partial: "/layouts/header" %>
      <% if current_page?(root_url) %>
        <%= render partial: "/layouts/alert" %>
        <%= yield %>
      <% else %>
        <div class="container">
          <%= render partial: "/layouts/alert" %>
          <%= yield %>
        </div>
      <% end %>
      <%= render partial: "/layouts/footer" %>
  </body>
</html>